# Generated by Django 4.2.1 on 2023-05-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='category',
            field=models.CharField(blank=True, choices=[('01', 'bootstrap関連'), ('02', 'python関連'), ('03', 'その他')], max_length=100, verbose_name='カテゴリ'),
        ),
    ]
