# Generated by Django 4.2.1 on 2023-05-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_snippet_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'python'), ('2', 'HTML'), ('3', 'CSS'), ('4', 'JavaScript'), ('5', 'SQL'), ('6', 'Java'), ('7', 'MarkDown')], max_length=100, verbose_name='カテゴリ'),
        ),
    ]
