# Generated by Django 4.2.1 on 2023-05-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_alter_snippet_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'python'), ('2', 'HTML'), ('3', 'CSS'), ('4', 'JavaScript'), ('5', 'SQL'), ('6', 'Java'), ('7', 'MarkDown')], max_length=100, verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='comment',
            name='code',
            field=models.TextField(blank=True, verbose_name='コード'),
        ),
    ]
