# Generated by Django 4.2.1 on 2023-05-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_comment_category_comment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='タイトル'),
        ),
    ]
