# Generated by Django 4.2.1 on 2023-05-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'python'), ('2', 'HTML'), ('3', 'CSS'), ('4', 'JavaScript'), ('5', 'SQL'), ('6', 'Java'), ('7', 'MarkDown'), ('8', 'Git')], max_length=100, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'python'), ('2', 'HTML'), ('3', 'CSS'), ('4', 'JavaScript'), ('5', 'SQL'), ('6', 'Java'), ('7', 'MarkDown'), ('8', 'Git')], max_length=100, verbose_name='カテゴリ'),
        ),
    ]
