# Generated by Django 4.2.1 on 2023-05-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_alter_comment_category_alter_snippet_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='snippet',
            table='snippets',
        ),
    ]
